[package]
name = "birthday_cake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.35.0"
nalgebra = { version = "0.30.1" }
fastrand = "1.7.0"
rgb = "0.8.33"
